# Generated by Django 2.2.6 on 2020-12-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados_comuns.DiretoriaRegional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados_comuns.Secretaria'),
        ),
    ]
