# Generated by Django 2.2.6 on 2020-12-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_auto_20201208_1209'),
        ('users', '0004_auto_20201208_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dre',
        ),
        migrations.AddField(
            model_name='user',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados_comuns.Setor'),
        ),
    ]
