# Generated by Django 2.2.6 on 2019-10-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='phonecell',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='logradouro',
            new_name='address',
        ),
    ]
