# Generated by Django 2.2.6 on 2019-10-17 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20191016_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='planta',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cellphone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d-]{9,10}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d-]{9,10}$')], verbose_name='Telefone'),
        ),
    ]
