# Generated by Django 2.2.6 on 2019-10-21 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_auto_20191017_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoImovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF / CNPJ')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CPF / CNPJ')),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d-]{9,10}$')], verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Proponente',
                'verbose_name_plural': 'Proponentes',
            },
        ),
        migrations.CreateModel(
            name='SME_Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Esta ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato Prefeitura',
                'verbose_name_plural': 'Contatos Prefeitura',
            },
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='neighborhood',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='state',
        ),
        migrations.AddField(
            model_name='imovel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.ContatoImovel'),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.AddField(
            model_name='imovel',
            name='proponente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.Proponente'),
            preserve_default=False,
        ),
    ]
