# Generated by Django 2.2.6 on 2019-10-22 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_auto_20191021_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.CharField(default='', max_length=255, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.CharField(default='', max_length=255, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(default='', max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default='', max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default='', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-\\_]{9,10}$')], verbose_name='Telefone'),
        ),
    ]
