# Generated by Django 2.2.6 on 2019-10-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0005_auto_20191022_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='latitude',
            field=models.CharField(max_length=255, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='longitude',
            field=models.CharField(max_length=255, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.CharField(max_length=255, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-\\_]{9,10}$')], verbose_name='Telefone'),
        ),
    ]
