# Generated by Django 2.2.6 on 2019-10-29 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0006_auto_20191028_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='planta',
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-\\_]{9,10}$')], verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='PlantaFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.FileField(upload_to='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.Imovel')),
            ],
        ),
    ]
