# Generated by Django 2.2.6 on 2019-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0007_auto_20191029_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='numero_iptu',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='tipo',
            field=models.CharField(choices=[(1, 'CORRETORA'), (2, 'PROCURACAO'), (3, 'DONO'), (4, 'ONG'), (5, 'OUTRO')], default='', max_length=2, verbose_name='Tipo'),
        ),
    ]
