# Generated by Django 2.2.6 on 2019-11-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0008_auto_20191031_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='numero_iptu',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numero IPTU'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proponente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.Proponente'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='tipo',
            field=models.CharField(choices=[(0, '----SELECIONE-----'), (1, 'Imobiliária'), (2, 'Procurador'), (3, 'Ong'), (4, 'Outro')], default=4, max_length=2, verbose_name='Tipo'),
        ),
    ]
