# Generated by Django 2.2.6 on 2019-11-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0009_auto_20191106_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proponente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.Proponente'),
        ),
    ]
