# Generated by Django 2.2.6 on 2019-12-11 17:36

from django.db import migrations, models

from ..sql_views import sql_create_view_listaimoveis, sql_drop_view_listaimoveis

class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0011_auto_20191206_1418'),
    ]

    operations = [
        migrations.RunSQL(
            sql_drop_view_listaimoveis,
            migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='proponente',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, '----SELECIONE-----'), (1, 'Imobiliária'), (2, 'Procurador'), (3, 'Ong'), (4, 'Outro')], default=4, verbose_name='Tipo'),
        ),
        migrations.RunSQL(
            sql_create_view_listaimoveis,
            sql_drop_view_listaimoveis
        ),

    ]
