# Generated by Django 2.2.6 on 2020-08-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0012_auto_20191211_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantafoto',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.Imovel'),
        ),
    ]
