# Generated by Django 3.1.3 on 2020-11-26 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('imovel', '0013_auto_20200806_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantafoto',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='celular',
            field=models.CharField(default='(11) 99111-1111', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='flag_type_docs',
            field=models.SmallIntegerField(choices=[(1, 'Fotos da Fachada'), (2, 'Fotos do Ambiente Interno'), (3, 'Cópia do IPTU ou ITR'), (4, 'Cópia da Planta ou Croqui')], default=1, verbose_name='Tipo Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='flag_type_file',
            field=models.SmallIntegerField(choices=[(1, 'Imagem'), (2, 'Documento')], default=1, verbose_name='Tipo Arquivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proponente',
            name='celular',
            field=models.CharField(default='(11) 99111-1111', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proponente',
            name='fk_type_bidders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.typebidders', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
