# Generated by Django 2.2.6 on 2021-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0013_auto_20200806_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(blank=True, choices=[('DUPLICACAO_IPTU', 'Duplicação de IPTU'), ('DUPLICACAO_ENDERECO', 'Duplicação de Endereço')], max_length=30, null=True, verbose_name='Situação'),
        ),
    ]
