# Generated by Django 2.2.6 on 2020-12-04 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0013_auto_20200806_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantafoto',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.RenameField(
            model_name='plantafoto',
            old_name='planta',
            new_name='arquivo',
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='celular',
            field=models.CharField(default='(11) 9 9111-1111', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 2345-6789 ou (XX) 1 2345-6789 Entre 8 ou 9 digitos', regex='(^\\(\\d{2}\\) [\\d\\-]{9,10}$)|(^\\(\\d{2}\\) \\d{1}\\ [\\d\\-]{9,10}$)')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='declaracao_responsabilidade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='tipo_arquivo',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Imagem'), (1, 'Documento')], null=True, verbose_name='Tipo Arquivo'),
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='tipo_documento',
            field=models.SmallIntegerField(choices=[(0, 'Fotos da Fachada'), (1, 'Fotos do Ambiente Interno'), (2, 'Fotos de Área Externa'), (3, 'Cópia do IPTU ou ITR'), (4, 'Cópia da Planta ou Croqui')], default=4, verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 2345-6789 ou (XX) 1 2345-6789 Entre 8 ou 9 digitos', regex='(^\\(\\d{2}\\) [\\d\\-]{9,10}$)|(^\\(\\d{2}\\) \\d{1}\\ [\\d\\-]{9,10}$)')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='situacao',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='tipo_proponente',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Não Informado'), (1, 'Proprietário'), (2, 'Representante Legal')], default=0, verbose_name='Tipo de Proponente'),
        ),
        migrations.AlterField(
            model_name='contatoimovel',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 2345-6789 ou (XX) 1 2345-6789 Entre 8 ou 9 digitos', regex='(^\\(\\d{2}\\) [\\d\\-]{9,10}$)|(^\\(\\d{2}\\) \\d{1}\\ [\\d\\-]{9,10}$)')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.ContatoImovel'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 2345-6789 ou (XX) 1 2345-6789 Entre 8 ou 9 digitos', regex='(^\\(\\d{2}\\) [\\d\\-]{9,10}$)|(^\\(\\d{2}\\) \\d{1}\\ [\\d\\-]{9,10}$)')], verbose_name='Telefone'),
        ),
    ]
