# Generated by Django 3.1.3 on 2020-11-27 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0013_auto_20200806_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProponente',
            fields=[
                ('pk_tipo_proponente', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Tipo de Proponente',
                'verbose_name_plural': 'Tipos de Proponentes',
            },
        ),
        migrations.AlterModelOptions(
            name='plantafoto',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='celular',
            field=models.CharField(default='(11) 9 9111-1111', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='flag_tipo_arquivo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Imagem'), (2, 'Documento')], null=True, verbose_name='Tipo Arquivo'),
        ),
        migrations.AddField(
            model_name='plantafoto',
            name='flag_tipo_documento',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Fotos da Fachada'), (2, 'Fotos do Ambiente Interno'), (3, 'Cópia do IPTU ou ITR'), (4, 'Cópia da Planta ou Croqui')], null=True, verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='celular',
            field=models.CharField(default='(11) 9 9111-1111', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='situacao',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='proponente',
            name='fk_tipo_proponente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='imovel.tipoproponente', verbose_name='Tipo'),
        ),
    ]
