# Generated by Django 2.2.6 on 2020-12-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_auto_20201208_1209'),
        ('imovel', '0015_auto_20201208_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='dre',
        ),
        migrations.AddField(
            model_name='imovel',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados_comuns.Setor'),
        ),
    ]
