# Generated by Django 2.2.6 on 2020-12-21 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0018_auto_20201220_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaImovel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bercario_i', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('bercario_ii', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('mini_grupo_i', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('mini_grupo_ii', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imovel.Imovel')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
