# Generated by Django 2.2.6 on 2020-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0019_demandaimovel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ('id',), 'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
