# Generated by Django 2.2.6 on 2020-12-28 14:39

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    PlantaFoto = apps.get_model('imovel', 'PlantaFoto')
    for plantafoto in PlantaFoto.objects.all():
        plantafoto.uuid = uuid.uuid4()
        plantafoto.save()


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0020_auto_20201222_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantafoto',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='plantafoto',
            name='uuid',
            field=models.UUIDField(unique=True)
        )
    ]
