# Generated by Django 2.2.6 on 2020-12-28 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0021_plantafoto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='nao_possui_iptu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantafoto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
