# Generated by Django 2.2.6 on 2021-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0022_auto_20201228_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='codigo_eol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo EOL'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='escola',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(default='Novo', max_length=255, verbose_name='Situação'),
        ),
    ]
