# Generated by Django 2.2.6 on 2021-02-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0025_auto_20210215_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandaimovel',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Atualização'),
        ),
    ]
