# Generated by Django 2.2.6 on 2021-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0026_demandaimovel_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao_duplicidade',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Situação Duplicidade'),
        ),
    ]
