# Generated by Django 3.1.3 on 2020-11-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typebidders',
            table='sme_type_bidders',
        ),
    ]
