# Generated by Django 3.1.3 on 2020-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201128_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddersbuildingsdocsimages',
            old_name='planta',
            new_name='doument',
        ),
        migrations.AddField(
            model_name='biddersbuildingsdocsimages',
            name='flag_type_docs',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Fotos da Fachada'), (2, 'Fotos do Ambiente Interno'), (3, 'Cópia do IPTU ou ITR'), (4, 'Cópia da Planta ou Croqui')], null=True, verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='biddersbuildingsdocsimages',
            name='flag_type_file',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Imagem'), (2, 'Documento')], null=True, verbose_name='Tipo Arquivo'),
        ),
    ]
