# Generated by Django 3.1.3 on 2020-11-29 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201129_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddersbuildingscontacts',
            name='address',
            field=models.CharField(default='Rua', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='biddersbuildingscontacts',
            name='cpf_cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=40, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='Documento de Identificação'),
        ),
        migrations.AlterUniqueTogether(
            name='biddersbuildingscontacts',
            unique_together={('cpf_cnpj', 'fk_bidders')},
        ),
    ]
