# Generated by Django 3.1.3 on 2020-11-29 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201129_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddersbuildingscontacts',
            name='document_id',
            field=models.CharField(default='00.000.000/0000-00', max_length=40, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterUniqueTogether(
            name='biddersbuildingscontacts',
            unique_together={('fk_bidders', 'document_id')},
        ),
        migrations.RemoveField(
            model_name='biddersbuildingscontacts',
            name='cpf_cnpj',
        ),
    ]
