# Generated by Django 3.1.3 on 2020-11-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201129_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiddersBuildingsContacts',
            new_name='BuildingsContacts',
        ),
        migrations.AlterModelOptions(
            name='buildingscontacts',
            options={'verbose_name': 'Contato do Imóvel', 'verbose_name_plural': 'Contatos dos Imóveis'},
        ),
        migrations.AddField(
            model_name='biddersbuildings',
            name='fk_bidders_contacts',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.BuildingsContacts', verbose_name='Contatos'),
        ),
        migrations.AlterField(
            model_name='buildingscontacts',
            name='fk_bidders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bidders', verbose_name='Proponente'),
        ),
        migrations.AlterModelTable(
            name='buildingscontacts',
            table='sme_buildings_contacts',
        ),
    ]
