# Generated by Django 3.1.3 on 2020-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201129_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddersbuildings',
            name='fk_bidders_contacts',
            field=models.ManyToManyField(to='home.BuildingsContacts', verbose_name='Contatos'),
        ),
    ]
