# Generated by Django 3.1.3 on 2020-11-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201129_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddersbuildings',
            name='latitude',
            field=models.CharField(max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='biddersbuildings',
            name='longitude',
            field=models.CharField(max_length=10, verbose_name='longitude'),
        ),
    ]
