# Generated by Django 3.1.3 on 2020-11-29 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddersbuildings',
            name='cep',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
    ]
