# Generated by Django 3.1.3 on 2020-11-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201129_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddersbuildingsdocsimages',
            old_name='doument',
            new_name='document',
        ),
    ]
