# Generated by Django 3.1.3 on 2020-11-30 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201129_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingscontacts',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
    ]
