# Generated by Django 3.1.3 on 2020-11-30 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_buildingscontacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingscontacts',
            name='cep',
            field=models.CharField(default='000000-000', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
    ]
