# Generated by Django 2.2.6 on 2020-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_auto_20201208_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprefeitura',
            name='dre',
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='dre',
            field=models.ManyToManyField(blank=True, related_name='subprefeituras', to='dados_comuns.DiretoriaRegional'),
        ),
    ]
