# Generated by Django 2.2.6 on 2020-12-19 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0003_auto_20201208_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFluxoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('status_evento', models.PositiveSmallIntegerField(choices=[(0, 'Aguardando análise prévia da SME'), (1, 'Enviado à COMPAPRE'), (2, 'Aguardando relatório de vistoria'), (3, 'Aguardando laudo de valor locatício'), (4, 'Aprovado'), (5, 'Enviado à DRE'), (6, 'Finalizado'), (7, 'Cancelado')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(upload_to='')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anexos', to='dados_comuns.LogFluxoStatus')),
            ],
        ),
    ]
