# Generated by Django 2.2.6 on 2020-12-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0016_auto_20201208_1819'),
        ('dados_comuns', '0004_anexolog_logfluxostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfluxostatus',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.Imovel'),
        ),
    ]
