# Generated by Django 2.2.6 on 2020-12-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_logfluxostatus_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfluxostatus',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imovel.Imovel'),
        ),
    ]
