# Generated by Django 2.2.6 on 2020-12-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0006_auto_20201219_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfluxostatus',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando análise prévia da SME'), (1, 'Enviado à COMAPRE'), (2, 'Aguardando relatório de vistoria'), (3, 'Aguardando laudo de valor locatício'), (4, 'Aprovado'), (5, 'Enviado à DRE'), (6, 'Finalizado'), (7, 'Cancelado')]),
        ),
    ]
