# Generated by Django 2.2.6 on 2020-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0007_auto_20201220_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfluxostatus',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação realizada'), (1, 'SME analisa previamente'), (2, 'Enviado à COMAPRE'), (3, 'Aguardando relatório de vistoria'), (4, 'Aguardando laudo de valor locatício'), (5, 'Aprovado'), (6, 'Enviado à DRE'), (7, 'Finalizado'), (8, 'Cancelado')]),
        ),
    ]
