# Generated by Django 2.2.6 on 2021-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0010_auto_20210106_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfluxostatus',
            name='data_agendada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data agendada'),
        ),
        migrations.AddField(
            model_name='logfluxostatus',
            name='email_enviado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Email enviado'),
        ),
        migrations.AlterField(
            model_name='logfluxostatus',
            name='status_evento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitação Realizada'), (1, 'SME analisou previamente'), (2, 'Finalizado - Área Insuficiente'), (3, 'Finalizado - Demanda Insuficiente'), (4, 'Finalizado - Não atende as necessidades da SME'), (5, 'Enviado à COMAPRE'), (6, 'Agendamento da vistoria'), (7, 'Aguardando relatório de vistoria'), (8, 'Relatório da vistoria'), (9, 'Aguardando laudo de valor locatício'), (10, 'Laudo de valor locatício'), (11, 'Vistoria aprovada'), (12, 'Vistoria reprovada'), (13, 'Enviado à DRE'), (14, 'Finalizado - Aprovado'), (15, 'Cancelado'), (16, 'Reativado')]),
        ),
    ]
