# Generated by Django 2.2.6 on 2021-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0011_auto_20210201_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexolog',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AddField(
            model_name='anexolog',
            name='tipo_arquivo',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Imagem'), (1, 'Documento')], null=True, verbose_name='Tipo Arquivo'),
        ),
        migrations.AddField(
            model_name='anexolog',
            name='tipo_documento',
            field=models.SmallIntegerField(choices=[(0, 'Relatório de vistoria'), (1, 'Relatório fotográfico'), (2, 'Planta atual'), (3, 'Planta com adequações'), (4, 'Plano de adequação'), (5, 'Laudo de valor locatício')], default=4, verbose_name='Tipo Documento'),
        ),
    ]
