# Generated by Django 2.2.6 on 2021-05-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0014_auto_20210215_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfluxostatus',
            options={'ordering': ('id',)},
        ),
    ]
